language: bash
services: docker

branches:
  only:
    - master

env:
  - FOLDER=7.4/buster/zts TAGS=7.4-zts,7.4.14-zts,7.4-buster-zts,7.4.14-buster-zts
  - FOLDER=7.4/alpine3.13/zts TAGS=7.4-alpine-zts,7.4.14-alpine-zts,7.4-alpine3.13-zts,7.4.14-alpine3.13-zts
  - FOLDER=7.4/alpine3.12/zts TAGS=7.4-alpine3.12-zts,7.4.14-alpine3.12-zts
  - FOLDER=7.4/alpine3.11/zts TAGS=7.4-alpine3.11-zts,7.4.14-alpine3.11-zts
  - FOLDER=7.4/buster/fpm TAGS=7.4-fpm,7.4.14-fpm,7.4-buster-fpm,7.4.14-buster-fpm
  - FOLDER=7.4/alpine3.13/fpm TAGS=7.4-alpine-fpm,7.4.14-alpine-fpm,7.4-alpine3.13-fpm,7.4.14-alpine3.13-fpm
  - FOLDER=7.4/alpine3.12/fpm TAGS=7.4-alpine3.12-fpm,7.4.14-alpine3.12-fpm
  - FOLDER=7.4/alpine3.11/fpm TAGS=7.4-alpine3.11-fpm,7.4.14-alpine3.11-fpm
  - FOLDER=7.4/buster/cli TAGS=7.4,7.4.14,7.4-cli,7.4.14-cli,7.4-buster,7.4.14-buster,7.4-buster-cli,7.4.14-buster-cli
  - FOLDER=7.4/alpine3.13/cli TAGS=7.4-alpine,7.4.14-alpine,7.4-alpine-cli,7.4-alpine3.13,7.4.14-alpine-cli,7.4.14-alpine3.13,7.4-alpine3.13-cli,7.4.14-alpine3.13-cli
  - FOLDER=7.4/alpine3.12/cli TAGS=7.4-alpine3.12,7.4.14-alpine3.12,7.4-alpine3.12-cli,7.4.14-alpine3.12-cli
  - FOLDER=7.4/alpine3.11/cli TAGS=7.4-alpine3.11,7.4.14-alpine3.11,7.4-alpine3.11-cli,7.4.14-alpine3.11-cli
  - FOLDER=7.4/buster/apache TAGS=7.4-apache,7.4.14-apache,7.4-buster-apache,7.4.14-buster-apache
  - FOLDER=7.3/buster/zts TAGS=7.3-zts,7.3.26-zts,7.3-buster-zts,7.3.26-buster-zts
  - FOLDER=7.3/alpine3.13/zts TAGS=7.3-alpine-zts,7.3.26-alpine-zts,7.3-alpine3.13-zts,7.3.26-alpine3.13-zts
  - FOLDER=7.3/alpine3.12/zts TAGS=7.3-alpine3.12-zts,7.3.26-alpine3.12-zts
  - FOLDER=7.3/alpine3.11/zts TAGS=7.3-alpine3.11-zts,7.3.26-alpine3.11-zts
  - FOLDER=7.3/buster/fpm TAGS=7.3-fpm,7.3.26-fpm,7.3-buster-fpm,7.3.26-buster-fpm
  - FOLDER=7.3/alpine3.13/fpm TAGS=7.3-alpine-fpm,7.3.26-alpine-fpm,7.3-alpine3.13-fpm,7.3.26-alpine3.13-fpm
  - FOLDER=7.3/alpine3.12/fpm TAGS=7.3-alpine3.12-fpm,7.3.26-alpine3.12-fpm
  - FOLDER=7.3/alpine3.11/fpm TAGS=7.3-alpine3.11-fpm,7.3.26-alpine3.11-fpm
  - FOLDER=7.3/buster/cli TAGS=7.3,7.3.26,7.3-cli,7.3.26-cli,7.3-buster,7.3.26-buster,7.3-buster-cli,7.3.26-buster-cli
  - FOLDER=7.3/alpine3.13/cli TAGS=7.3-alpine,7.3.26-alpine,7.3-alpine-cli,7.3-alpine3.13,7.3.26-alpine-cli,7.3.26-alpine3.13,7.3-alpine3.13-cli,7.3.26-alpine3.13-cli
  - FOLDER=7.3/alpine3.12/cli TAGS=7.3-alpine3.12,7.3.26-alpine3.12,7.3-alpine3.12-cli,7.3.26-alpine3.12-cli
  - FOLDER=7.3/alpine3.11/cli TAGS=7.3-alpine3.11,7.3.26-alpine3.11,7.3-alpine3.11-cli,7.3.26-alpine3.11-cli
  - FOLDER=7.3/buster/apache TAGS=7.3-apache,7.3.26-apache,7.3-buster-apache,7.3.26-buster-apache
  - FOLDER=7.2/buster/zts TAGS=7.2-zts,7.2.34-zts,7.2-buster-zts,7.2.34-buster-zts
  - FOLDER=7.2/alpine3.12/zts TAGS=7.2-alpine-zts,7.2.34-alpine-zts,7.2-alpine3.12-zts,7.2.34-alpine3.12-zts
  - FOLDER=7.2/alpine3.11/zts TAGS=7.2-alpine3.11-zts,7.2.34-alpine3.11-zts
  - FOLDER=7.2/buster/fpm TAGS=7.2-fpm,7.2.34-fpm,7.2-buster-fpm,7.2.34-buster-fpm
  - FOLDER=7.2/alpine3.12/fpm TAGS=7.2-alpine-fpm,7.2.34-alpine-fpm,7.2-alpine3.12-fpm,7.2.34-alpine3.12-fpm
  - FOLDER=7.2/alpine3.11/fpm TAGS=7.2-alpine3.11-fpm,7.2.34-alpine3.11-fpm
  - FOLDER=7.2/buster/cli TAGS=7.2,7.2.34,7.2-cli,7.2.34-cli,7.2-buster,7.2.34-buster,7.2-buster-cli,7.2.34-buster-cli
  - FOLDER=7.2/alpine3.12/cli TAGS=7.2-alpine,7.2.34-alpine,7.2-alpine-cli,7.2-alpine3.12,7.2.34-alpine-cli,7.2.34-alpine3.12,7.2-alpine3.12-cli,7.2.34-alpine3.12-cli
  - FOLDER=7.2/alpine3.11/cli TAGS=7.2-alpine3.11,7.2.34-alpine3.11,7.2-alpine3.11-cli,7.2.34-alpine3.11-cli
  - FOLDER=7.2/buster/apache TAGS=7.2-apache,7.2.34-apache,7.2-buster-apache,7.2.34-buster-apache

script:
  - cd $FOLDER
  - IMAGESLIST=()
  - IFS=, read -a TAGSLIST <<< "$TAGS"
  - docker build .
  - |
    for TAG in "${TAGSLIST[@]}"
    do
      IMAGE="solune/symfony:${TAG}"
      docker build . -t "${IMAGE}"
      IMAGESLIST+=("${IMAGE}")
    done
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    for IMAGE in "${IMAGESLIST[@]}"
    do
      echo "Pushing $IMAGE to the registry"
      docker push "${IMAGE}"
    done
