language: bash
services: docker

branches:
  only:
    - master

env:
  - FOLDER=7.2/buster/cli/ TAGS=7.2.28-cli-buster
  - FOLDER=7.2/buster/apache/ TAGS=7.2.28-apache-buster
  - FOLDER=7.2/buster/fpm/ TAGS=7.2.28-fpm-buster
  - FOLDER=7.2/buster/zts/ TAGS=7.2.28-zts-buster
  - FOLDER=7.2/stretch/cli/ TAGS=7.2.28-cli-stretch
  - FOLDER=7.2/stretch/apache/ TAGS=7.2.28-apache-stretch
  - FOLDER=7.2/stretch/fpm/ TAGS=7.2.28-fpm-stretch
  - FOLDER=7.2/stretch/zts/ TAGS=7.2.28-zts-stretch
  - FOLDER=7.2/alpine3.11/cli/ TAGS=7.2.28-cli-alpine3.11
  - FOLDER=7.2/alpine3.11/fpm/ TAGS=7.2.28-fpm-alpine3.11
  - FOLDER=7.2/alpine3.11/zts/ TAGS=7.2.28-zts-alpine3.11
  - FOLDER=7.2/alpine3.10/cli/ TAGS=7.2.28-cli-alpine3.10
  - FOLDER=7.2/alpine3.10/fpm/ TAGS=7.2.28-fpm-alpine3.10
  - FOLDER=7.2/alpine3.10/zts/ TAGS=7.2.28-zts-alpine3.10
  - FOLDER=7.3/buster/cli/ TAGS=7.3.15-cli-buster
  - FOLDER=7.3/buster/apache/ TAGS=7.3.15-apache-buster
  - FOLDER=7.3/buster/fpm/ TAGS=7.3.15-fpm-buster
  - FOLDER=7.3/buster/zts/ TAGS=7.3.15-zts-buster
  - FOLDER=7.3/stretch/cli/ TAGS=7.3.15-cli-stretch
  - FOLDER=7.3/stretch/apache/ TAGS=7.3.15-apache-stretch
  - FOLDER=7.3/stretch/fpm/ TAGS=7.3.15-fpm-stretch
  - FOLDER=7.3/stretch/zts/ TAGS=7.3.15-zts-stretch
  - FOLDER=7.3/alpine3.11/cli/ TAGS=7.3.15-cli-alpine3.11
  - FOLDER=7.3/alpine3.11/fpm/ TAGS=7.3.15-fpm-alpine3.11
  - FOLDER=7.3/alpine3.11/zts/ TAGS=7.3.15-zts-alpine3.11
  - FOLDER=7.3/alpine3.10/cli/ TAGS=7.3.15-cli-alpine3.10
  - FOLDER=7.3/alpine3.10/fpm/ TAGS=7.3.15-fpm-alpine3.10
  - FOLDER=7.3/alpine3.10/zts/ TAGS=7.3.15-zts-alpine3.10
  - FOLDER=7.4/buster/cli/ TAGS=7.4.3-cli-buster
  - FOLDER=7.4/buster/apache/ TAGS=7.4.3-apache-buster
  - FOLDER=7.4/buster/fpm/ TAGS=7.4.3-fpm-buster
  - FOLDER=7.4/buster/zts/ TAGS=7.4.3-zts-buster
  - FOLDER=7.4/alpine3.11/cli/ TAGS=7.4.3-cli-alpine3.11
  - FOLDER=7.4/alpine3.11/fpm/ TAGS=7.4.3-fpm-alpine3.11
  - FOLDER=7.4/alpine3.11/zts/ TAGS=7.4.3-zts-alpine3.11
  - FOLDER=7.4/alpine3.10/cli/ TAGS=7.4.3-cli-alpine3.10
  - FOLDER=7.4/alpine3.10/fpm/ TAGS=7.4.3-fpm-alpine3.10
  - FOLDER=7.4/alpine3.10/zts/ TAGS=7.4.3-zts-alpine3.10

script:
  - cd $FOLDER
  - IMAGESLIST=()
  - IFS=, read -a TAGSLIST <<< "$TAGS"
  - |
    for TAG in "${TAGSLIST[@]}"
    do
      IMAGE="solune/symfony:${TAG}"
      echo "Building image ${TAG}"
      docker build . -t "${IMAGE}"
      IMAGESLIST+=("${IMAGE}")
    done

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    for IMAGE in "${IMAGESLIST[@]}"
    do
      echo "Pushing $IMAGE to the registry"
      docker push "${IMAGE}"
    done
