language: bash
services: docker

branches:
  only:
    - master

env:
  - FOLDER=7.1/stretch/cli/ TAG=7.1.28-cli-stretch
  - FOLDER=7.1/stretch/apache/ TAG=7.1.28-apache-stretch
  - FOLDER=7.1/stretch/fpm/ TAG=7.1.28-fpm-stretch
  - FOLDER=7.1/stretch/zts/ TAG=7.1.28-zts-stretch
  - FOLDER=7.1/jessie/cli/ TAG=7.1.28-cli-jessie
  - FOLDER=7.1/jessie/apache/ TAG=7.1.28-apache-jessie
  - FOLDER=7.1/jessie/fpm/ TAG=7.1.28-fpm-jessie
  - FOLDER=7.1/jessie/zts/ TAG=7.1.28-zts-jessie
  - FOLDER=7.1/alpine3.9/cli/ TAG=7.1.28-cli-alpine3.9
  - FOLDER=7.1/alpine3.9/fpm/ TAG=7.1.28-fpm-alpine3.9
  - FOLDER=7.1/alpine3.9/zts/ TAG=7.1.28-zts-alpine3.9
  - FOLDER=7.1/alpine3.8/cli/ TAG=7.1.28-cli-alpine3.8
  - FOLDER=7.1/alpine3.8/fpm/ TAG=7.1.28-fpm-alpine3.8
  - FOLDER=7.1/alpine3.8/zts/ TAG=7.1.28-zts-alpine3.8
  - FOLDER=7.2/stretch/cli/ TAG=7.2.17-cli-stretch
  - FOLDER=7.2/stretch/apache/ TAG=7.2.17-apache-stretch
  - FOLDER=7.2/stretch/fpm/ TAG=7.2.17-fpm-stretch
  - FOLDER=7.2/stretch/zts/ TAG=7.2.17-zts-stretch
  - FOLDER=7.2/alpine3.9/cli/ TAG=7.2.17-cli-alpine3.9
  - FOLDER=7.2/alpine3.9/fpm/ TAG=7.2.17-fpm-alpine3.9
  - FOLDER=7.2/alpine3.9/zts/ TAG=7.2.17-zts-alpine3.9
  - FOLDER=7.2/alpine3.8/cli/ TAG=7.2.17-cli-alpine3.8
  - FOLDER=7.2/alpine3.8/fpm/ TAG=7.2.17-fpm-alpine3.8
  - FOLDER=7.2/alpine3.8/zts/ TAG=7.2.17-zts-alpine3.8
  - FOLDER=7.3/stretch/cli/ TAG=7.3.4-cli-stretch
  - FOLDER=7.3/stretch/apache/ TAG=7.3.4-apache-stretch
  - FOLDER=7.3/stretch/fpm/ TAG=7.3.4-fpm-stretch
  - FOLDER=7.3/stretch/zts/ TAG=7.3.4-zts-stretch
  - FOLDER=7.3/alpine3.9/cli/ TAG=7.3.4-cli-alpine3.9
  - FOLDER=7.3/alpine3.9/fpm/ TAG=7.3.4-fpm-alpine3.9
  - FOLDER=7.3/alpine3.9/zts/ TAG=7.3.4-zts-alpine3.9
  - FOLDER=7.3/alpine3.8/cli/ TAG=7.3.4-cli-alpine3.8
  - FOLDER=7.3/alpine3.8/fpm/ TAG=7.3.4-fpm-alpine3.8
  - FOLDER=7.3/alpine3.8/zts/ TAG=7.3.4-zts-alpine3.8

script:
  - IMAGE="solune/symfony:${TAG}"
  - echo "Building image ${TAG}";
  - cd $FOLDER
  - docker build . -t "${IMAGE}"

after_success:
  - echo "Pushing $IMAGE to the registry"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE"
