language: bash
services: docker

branches:
  only:
    - master

env:
  - FOLDER=7.1/stretch/cli/ TAGS=7.1.28-cli-stretch
  - FOLDER=7.1/stretch/apache/ TAGS=7.1.28-apache-stretch
  - FOLDER=7.1/stretch/fpm/ TAGS=7.1.28-fpm-stretch
  - FOLDER=7.1/stretch/zts/ TAGS=7.1.28-zts-stretch
  - FOLDER=7.1/jessie/cli/ TAGS=7.1.28-cli-jessie
  - FOLDER=7.1/jessie/apache/ TAGS=7.1.28-apache-jessie
  - FOLDER=7.1/jessie/fpm/ TAGS=7.1.28-fpm-jessie
  - FOLDER=7.1/jessie/zts/ TAGS=7.1.28-zts-jessie
  - FOLDER=7.1/alpine3.9/cli/ TAGS=7.1.28-cli-alpine3.9,7.1-cli,7.1.28,7.1
  - FOLDER=7.1/alpine3.9/fpm/ TAGS=7.1.28-fpm-alpine3.9,7.1-fpm
  - FOLDER=7.1/alpine3.9/zts/ TAGS=7.1.28-zts-alpine3.9,7.1-zts
  - FOLDER=7.1/alpine3.8/cli/ TAGS=7.1.28-cli-alpine3.8
  - FOLDER=7.1/alpine3.8/fpm/ TAGS=7.1.28-fpm-alpine3.8
  - FOLDER=7.1/alpine3.8/zts/ TAGS=7.1.28-zts-alpine3.8
  - FOLDER=7.2/stretch/cli/ TAGS=7.2.17-cli-stretch
  - FOLDER=7.2/stretch/apache/ TAGS=7.2.17-apache-stretch
  - FOLDER=7.2/stretch/fpm/ TAGS=7.2.17-fpm-stretch
  - FOLDER=7.2/stretch/zts/ TAGS=7.2.17-zts-stretch
  - FOLDER=7.2/alpine3.9/cli/ TAGS=7.2.17-cli-alpine3.9,7.2-cli,7.2.17,7.2
  - FOLDER=7.2/alpine3.9/fpm/ TAGS=7.2.17-fpm-alpine3.9,7.2-fpm
  - FOLDER=7.2/alpine3.9/zts/ TAGS=7.2.17-zts-alpine3.9,7.2-zts
  - FOLDER=7.2/alpine3.8/cli/ TAGS=7.2.17-cli-alpine3.8
  - FOLDER=7.2/alpine3.8/fpm/ TAGS=7.2.17-fpm-alpine3.8
  - FOLDER=7.2/alpine3.8/zts/ TAGS=7.2.17-zts-alpine3.8
  - FOLDER=7.3/stretch/cli/ TAGS=7.3.4-cli-stretch
  - FOLDER=7.3/stretch/apache/ TAGS=7.3.4-apache-stretch
  - FOLDER=7.3/stretch/fpm/ TAGS=7.3.4-fpm-stretch
  - FOLDER=7.3/stretch/zts/ TAGS=7.3.4-zts-stretch
  - FOLDER=7.3/alpine3.9/cli/ TAGS=7.3.4-cli-alpine3.9,7.3-cli,7.3.4,7.3
  - FOLDER=7.3/alpine3.9/fpm/ TAGS=7.3.4-fpm-alpine3.9,7.3-fpm
  - FOLDER=7.3/alpine3.9/zts/ TAGS=7.3.4-zts-alpine3.9,7.3-zts
  - FOLDER=7.3/alpine3.8/cli/ TAGS=7.3.4-cli-alpine3.8
  - FOLDER=7.3/alpine3.8/fpm/ TAGS=7.3.4-fpm-alpine3.8
  - FOLDER=7.3/alpine3.8/zts/ TAGS=7.3.4-zts-alpine3.8

script:
  - cd $FOLDER
  - IFS=, read -a TAGSLIST <<< "$TAGS"
  - |
    for TAG in "${TAGSLIST[@]}"
    do
      IMAGE="solune/symfony:${TAG}"
      echo "Building image ${TAG}";
      docker build . -t "${IMAGE}"
    done

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    for TAG in "${TAGSLIST[@]}"
    do
      echo "Pushing $IMAGE to the registry"
      docker push "$IMAGE"
    done
