language: bash
services: docker

branches:
  only:
    - master

env:
  - FOLDER=7.1/stretch/cli/ TAGS=7.1.33-cli-stretch
  - FOLDER=7.1/stretch/apache/ TAGS=7.1.33-apache-stretch
  - FOLDER=7.1/stretch/fpm/ TAGS=7.1.33-fpm-stretch
  - FOLDER=7.1/stretch/zts/ TAGS=7.1.33-zts-stretch
  - FOLDER=7.1/jessie/cli/ TAGS=7.1.33-cli-jessie
  - FOLDER=7.1/jessie/apache/ TAGS=7.1.33-apache-jessie
  - FOLDER=7.1/jessie/fpm/ TAGS=7.1.33-fpm-jessie
  - FOLDER=7.1/jessie/zts/ TAGS=7.1.33-zts-jessie
  - FOLDER=7.1/alpine3.9/cli/ TAGS=7.1.33-cli-alpine3.9,7.1-cli,7.1.33,7.1
  - FOLDER=7.1/alpine3.9/fpm/ TAGS=7.1.33-fpm-alpine3.9,7.1-fpm
  - FOLDER=7.1/alpine3.9/zts/ TAGS=7.1.33-zts-alpine3.9,7.1-zts
  - FOLDER=7.1/alpine3.8/cli/ TAGS=7.1.33-cli-alpine3.8
  - FOLDER=7.1/alpine3.8/fpm/ TAGS=7.1.33-fpm-alpine3.8
  - FOLDER=7.1/alpine3.8/zts/ TAGS=7.1.33-zts-alpine3.8
  - FOLDER=7.2/stretch/cli/ TAGS=7.2.27-cli-stretch
  - FOLDER=7.2/stretch/apache/ TAGS=7.2.27-apache-stretch
  - FOLDER=7.2/stretch/fpm/ TAGS=7.2.27-fpm-stretch
  - FOLDER=7.2/stretch/zts/ TAGS=7.2.27-zts-stretch
  - FOLDER=7.2/alpine3.9/cli/ TAGS=7.2.27-cli-alpine3.9,7.2-cli,7.2.27,7.2
  - FOLDER=7.2/alpine3.9/fpm/ TAGS=7.2.27-fpm-alpine3.9,7.2-fpm
  - FOLDER=7.2/alpine3.9/zts/ TAGS=7.2.27-zts-alpine3.9,7.2-zts
  - FOLDER=7.2/alpine3.8/cli/ TAGS=7.2.27-cli-alpine3.8
  - FOLDER=7.2/alpine3.8/fpm/ TAGS=7.2.27-fpm-alpine3.8
  - FOLDER=7.2/alpine3.8/zts/ TAGS=7.2.27-zts-alpine3.8
  - FOLDER=7.3/stretch/cli/ TAGS=7.3.14-cli-stretch
  - FOLDER=7.3/stretch/apache/ TAGS=7.3.14-apache-stretch
  - FOLDER=7.3/stretch/fpm/ TAGS=7.3.14-fpm-stretch
  - FOLDER=7.3/stretch/zts/ TAGS=7.3.14-zts-stretch
  - FOLDER=7.3/alpine3.9/cli/ TAGS=7.3.14-cli-alpine3.9,7.3-cli,7.3.14,7.3
  - FOLDER=7.3/alpine3.9/fpm/ TAGS=7.3.14-fpm-alpine3.9,7.3-fpm
  - FOLDER=7.3/alpine3.9/zts/ TAGS=7.3.14-zts-alpine3.9,7.3-zts
  - FOLDER=7.3/alpine3.8/cli/ TAGS=7.3.14-cli-alpine3.8
  - FOLDER=7.3/alpine3.8/fpm/ TAGS=7.3.14-fpm-alpine3.8
  - FOLDER=7.3/alpine3.8/zts/ TAGS=7.3.14-zts-alpine3.8

script:
  - cd $FOLDER
  - IMAGESLIST=()
  - IFS=, read -a TAGSLIST <<< "$TAGS"
  - |
    for TAG in "${TAGSLIST[@]}"
    do
      IMAGE="solune/symfony:${TAG}"
      echo "Building image ${TAG}"
      docker build . -t "${IMAGE}"
      IMAGESLIST+=("${IMAGE}")
    done

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    for IMAGE in "${IMAGESLIST[@]}"
    do
      echo "Pushing $IMAGE to the registry"
      docker push "${IMAGE}"
    done
